blank_issues_enabled: false
contact_links:
  - name: Security Policy
    url: https://github.com/Chapter-39/app-template/security/policy
    about: Please report security vulnerabilities privately following our policy.

