name: CI

on:
  push: {}
  pull_request: {}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Prettier check
        run: npm run format:check

      - name: Test (if present)
        if: "${{ hashFiles('package.json') != '' }}"
        run: |
          if npm run | grep -q " test\b"; then
            npm test
          else
            echo "No test script found; skipping"
          fi
