name: Deploy preview to Netlify

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PKG_GH_READ }}

      - name: Build
        run: npm run build
        env:
          VITE_APPLE_TEAM_ID: ${{ vars.VITE_APPLE_TEAM_ID }}
          VITE_APPLE_BUNDLE_ID: ${{ vars.VITE_APPLE_BUNDLE_ID }}
          VITE_APPLE_SERVICE_ID: ${{ vars.VITE_APPLE_SERVICE_ID }}
          VITE_APPLE_REDIRECT_URI: ${{ vars.VITE_APPLE_REDIRECT_URI }}
          VITE_APPLE_SCOPE: ${{ vars.VITE_APPLE_SCOPE }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ vars.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT }}
          SENTRY_RELEASE: pr-${{ github.event.number }}

      - name: Deploy (preview)
        run: |
          npx -y netlify-cli@17 deploy \
            --dir=dist \
            --site "${{ secrets.NETLIFY_SITE_ID }}" \
            --auth "${{ secrets.NETLIFY_AUTH_TOKEN }}" \
            --alias "pr-${{ github.event.number }}" \
            --message "PR #${{ github.event.number }} - ${{ github.sha }}"
