name: Release Sentry Sourcemaps

on:
  release:
    types: [published]

permissions:
  contents: read

concurrency:
  group: sentry-release-${{ github.event.release.tag_name }}
  cancel-in-progress: false

jobs:
  upload-sourcemaps:
    name: Build and upload to Sentry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Install
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Build (uploads sourcemaps via Sentry Vite Plugin)
        run: npm run build
        env:
          # Sentry auth and project info (configure these as GitHub Secrets)
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          VITE_SENTRY_ORG: ${{ secrets.VITE_SENTRY_ORG }}
          VITE_SENTRY_PROJECT: ${{ secrets.VITE_SENTRY_PROJECT }}
          # Optionally tie the release to the tag name
          SENTRY_RELEASE: ${{ github.event.release.tag_name }}
          # Ensure production build path
          NODE_ENV: production
