name: Deploy release to Netlify

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: read

concurrency:
  group: netlify-release-${{ github.event.release.tag_name }}
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy Job
    environment: production
    runs-on: ubuntu-latest
    env:
      # Build-time env para Vite
      VITE_APPLE_TEAM_ID: ${{ vars.VITE_APPLE_TEAM_ID }}
      VITE_APPLE_BUNDLE_ID: ${{ vars.VITE_APPLE_BUNDLE_ID }}
      VITE_APPLE_SERVICE_ID: ${{ vars.VITE_APPLE_SERVICE_ID }}
      VITE_APPLE_REDIRECT_URI: ${{ vars.VITE_APPLE_REDIRECT_URI }}
      VITE_APPLE_SCOPE: ${{ vars.VITE_APPLE_SCOPE }}
      # Sentry y Node
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ vars.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT }}
      SENTRY_RELEASE: ${{ github.event.release.tag_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PKG_GH_READ }}

      - name: Assert Vite env
        run: |
          echo "VITE_APPLE_TEAM_ID=$VITE_APPLE_TEAM_ID"
          node -e "console.log('node sees', process.env.VITE_APPLE_TEAM_ID || 'undefined')"

      - name: Build (uploads sourcemaps via Sentry Vite Plugin)
        run: npm run build

      - name: Deploy to Netlify (no build, no UI overrides)
        run: |
          npx -y netlify-cli@17 deploy \
            --prod \
            --dir=dist \
            --site "${{ secrets.NETLIFY_SITE_ID }}" \
            --auth "${{ secrets.NETLIFY_AUTH_TOKEN }}" \
            --message "Release ${{ github.event.release.tag_name }}"
