name: Release Netlify Deploy

on:
  release:
    types: [published]

permissions:
  contents: read

concurrency:
  group: netlify-release-${{ github.event.release.tag_name }}
  cancel-in-progress: false

jobs:
  deploy:
    name: Build and deploy to Netlify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Install
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      - name: Deploy to Netlify (prod)
        uses: netlify/actions/cli@v4
        with:
          args: deploy --dir=dist --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
