name: Release Netlify Deploy

on:
  release:
    types: [published]

permissions:
  contents: read

concurrency:
  group: netlify-release-${{ github.event.release.tag_name }}
  cancel-in-progress: false

jobs:
  deploy:
    name: Build and deploy to Netlify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Install
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PKG_GH_READ }}

      - name: Build (uploads sourcemaps via Sentry Vite Plugin)
        run: npm run build
        env:
          # Apple Sign In environment variables (configure these as GitHub Secrets)
          VITE_APPLE_TEAM_ID: ${{ secrets.VITE_APPLE_TEAM_ID }}
          VITE_APPLE_BUNDLE_ID: ${{ secrets.VITE_APPLE_BUNDLE_ID }}
          VITE_APPLE_SERVICE_ID: ${{ secrets.VITE_APPLE_SERVICE_ID }}
          VITE_APPLE_REDIRECT_URI: ${{ secrets.VITE_APPLE_REDIRECT_URI }}
          VITE_APPLE_SCOPE: ${{ secrets.VITE_APPLE_SCOPE }}
          # Sentry auth and project info (configure these as GitHub Secrets)
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          # Optionally tie the release to the tag name
          SENTRY_RELEASE: ${{ github.event.release.tag_name }}
          # Ensure production build path
          NODE_ENV: production

      - uses: netlify/actions/cli@master
        with:
          args: deploy --dir=dist --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_AUTH_TOKEN }}
